---
title: "R-PUBG_StrategiesAnalysis"
description: |
  A short description of the post.
author:
  - name: Jiayi Wang
    url: https://www.linkedin.com/in/jiayi-wang-smu/
date: 08-06-2021
output:
  distill::distill_article:
    self_contained: false
    toc: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
The PlayerUnknown's Battlegrounds (PUBG) is a battle royal game with hundreds of million players. 100 players parachute onto an island and scavenge for weapons and equipment to kill others while avoiding getting killed themselves. 

To win the first placement, players use multiple strategies from their experience. Our team aims to enable players to get better ranks by extracting the relationships among death rate and different strategies from over 720K matches which give more statistical inspirations.

# Data Preparation
To provide a clear picture of the PUBG match strategy analysis and to propose appropriate suggestions, in this project, we used the PUBG Match Deaths and Statistics Datasets. It is a publicly available dataset that can be found on [Kaggle](https://www.kaggle.com/skihikingkevin/pubg-match-deaths), containing over 720K competitive matches from the PUBG, extracted from a game tracker website, [pubg.op.gg](https://pubg.op.gg/).

Instead of using all the data files provided in the original dataset, we mainly focus on 5 divided datasets of deaths in the match map ERANGEL which records above 80% of death events occurred within the 720K matches. Since the datasets is very huge, 2GB for each file, so we only take one of 5 datasets mentioned above, containing about 120K records of match.

Before the analysis, we cleaned the dataset with following main steps:

* 1. Exclude all the possible missing values.

* 2. Remove the data that seemed like it was generated by a cheating program.

* 3. Put away the data that the killer’s position is over 800,000 to ensure the data of the killer's position in this project is exactly between 0 and 800,000.

# Descriptive and Inferential Statistics

##. Landing Analysis
After the game started, players would set off to different places. In generally, there are 2 main strategies. The first strategy, players are obsessed with high-value places which have good qualities and quantities of weapons and armours. Those high value places are also highly risky 
because it fascinates other players as well. You can always hear gunshots from there.

The following picture was provided by [PUBG official](https://pubg.op.gg/maps/statistics) which shows the distribution of valuable weapons. Indeed, those high frequency areas are also what we call downtown areas which have many buildings located next to each other.







